var heroData = {
	'purpleArr':
		[
			{
			'name':'陆三金',
			'intro':'平安票号少东家，现任龙门镖局当家。体质文弱，是一枚智慧型富二代，金融界天才，看重金钱但更重情义。',
			'wuqi':'扇子',
			'dir':'远程',
			'xl':8186,
			'wf':869,
			'nf':610,
			'specialSrc':'<img src="img/k-lsj.png" alt="">',
			'skill':'<li><span class="title_name">掌柜振奋：</span><span class="title_intro">随机振奋一名前排队友，增加其物理防御。</span></li><li><span class="title_name">平安保镖：</span><span class="title_intro">召唤两个保镖连射火枪突袭敌人，造成物理伤害。</span></li><li><span class="title_name">护心内丹：</span><span class="title_intro">服用护心内丹，永久增加自身魔法防御。</span></li><li><span class="title_name">背水一战（大招）：</span><span class="title_intro">吹起号角提升全员士气，增加已方全体单位魔法攻击力。</span></li>',
			'bsqy':'<li><span class="title_name">陆三水：</span><span class="title_intro">三金的妹妹，小时候被三金坑的团团转。</span></li><li><span class="title_name">陆三木：</span><span class="title_intro">三金的弟弟，孟子的忠实拥簇。</span></li>',
			'heroImgSrc_big':'<img src="img/b-lsj.png" alt="">',
			'heroImgSrc_small':'img/s-lsj.jpg'
			},
			{
			'name':'盛秋月',
			'intro':'龙门镖局少奶奶，前广东“地方社团民意代表”，喜欢暴力，专业闯祸。不过心地善良，是个合格的大姐大。',
			'wuqi':'单手刀',
			'dir':'近战',
			'xl':14188,
			'wf':972,
			'nf':567,
			'specialSrc':'<img src="img/k-sqy.png" alt="">',
			'skill':'<li><span class="title_name">桃花三刀：</span><span class="title_intro">对一个敌人狂砍三刀，造成物理伤害。</span></li><li><span class="title_name">情比金坚：</span><span class="title_intro">永久增加自身物理防御。</span></li><li><span class="title_name">刀法专精：</span><span class="title_intro">永久增加自身物理攻击。</span></li><li><span class="title_name">一姐号令（大招）：</span><span class="title_intro">召唤小弟冲入战场帮忙战斗。</span></li>',
			'bsqy':'<li><span class="title_name">糊糊：</span><span class="title_intro">秋月的儿子，逃学惯犯</span></li><li><span class="title_name">山鸡：</span><span class="title_intro">秋月的小弟，混社团时擅长打头阵</span></li>',
			'heroImgSrc_big':'<img src="img/b-sqy.png" alt="">',
			'heroImgSrc_small':'img/s-sqy.jpg'
			},
			{
			'name':'温良恭',
			'intro':'现任龙门镖局总镖头，处事圆滑，经验老到。年少时貌比潘安，女友遍天下，处处留情。',
			'wuqi':'长枪',
			'dir':'近战',
			'xl':11684,
			'wf':956,
			'nf':577,
			'specialSrc':'<img src="img/k-wlg.png" alt="">',
			'skill':'<li><span class="title_name">青龙出洞：</span><span class="title_intro">对当前单位连续攻击3次，造成物理伤害。</span></li><li><span class="title_name">火炎之魂：</span><span class="title_intro">火龙枪法的进阶枪术，在使用火龙乱舞技能后，能对命中的目标造成灼烧效果，持续造成物理伤害。</span></li><li><span class="title_name">潜龙勿用：</span><span class="title_intro">火龙枪法的高阶枪术，永久增加自身物理攻击力和暴击值。</span></li><li><span class="title_name">火龙乱舞（大招）：</span><span class="title_intro">打出一条火龙攻击直线上的敌人，造成大量物理伤害。</span></li>',
			'bsqy':'<li><span class="title_name">厉文婷：</span><span class="title_intro">恭叔的前女友，被甩之后性格大变。</span></li><li><span class="title_name">龚露：</span><span class="title_intro">恭叔的前女友，否认自己是处女座</span></li>',
			'heroImgSrc_big':'<img src="img/b-wlg.png" alt="">',
			'heroImgSrc_small':'img/s-wlg.jpg'
			},
			{
			'name':'白敬祺',
			'intro':'佟湘玉的儿子，体健貌端，志向高远，三观健康，多愁善感，喜欢得瑟，爱面子。',
			'wuqi':'无敌左轮枪',
			'dir':'远程',
			'xl':7818,
			'wf':836,
			'nf':415,
			'specialSrc':'<img src="img/k-bjq.png" alt="">',
			'skill':'<li><span class="title_name">漫天灰雨：</span><span class="title_intro">偷偷对敌方战场扔出一袋石灰，对造成物理伤害，并使区域内敌人致盲。</span></li><li><span class="title_name">风掣三击：</span><span class="title_intro">永久增加自身物理攻击力。</span></li><li><span class="title_name">摘星踏月：</span><span class="title_intro">永久增加自身闪避。</span></li><li><span class="title_name">进击的小爷（大招）：</span><span class="title_intro">连续射出大量的子弹，攻击扇形范围内敌人，造成海量物理伤害。</span></li>',
			'bsqy':'<li><span class="title_name">浩天：</span><span class="title_intro">敬祺的发小，似乎对敬琪有不一样的感情。</span></li><li><span class="title_name">冉香：</span><span class="title_intro">与敬琪约定来世再见。</span></li>',
			'heroImgSrc_big':'<img src="img/b-bjq.png" alt="">',
			'heroImgSrc_small':'img/s-bjq.jpg'
			},
			{
			'name':'吕青橙',
			'intro':'龙门镖局趟子手，个性单纯，古灵精怪，练就惊涛掌第七层，武功高强。',
			'wuqi':'拳掌',
			'dir':'近战',
			'xl':9908,
			'wf':875,
			'nf':775,
			'specialSrc':'<img src="img/k-lqc.png" alt="">',
			'skill':'<li><span class="title_name">沙场点兵：</span><span class="title_intro">瞬间移动到目标单位身前，将目标点穴定身，并造成魔法伤害，定身状态中不可移动和攻击，并且降低魔法防御。</span></li><li><span class="title_name">摧筋断骨：</span><span class="title_intro">永久增加自身魔法攻击力。</span></li><li><span class="title_name">芙蓉惊涛掌：</span><span class="title_intro">永久增加自身暴击值。</span></li><li><span class="title_name">惊涛骇浪（大招）：</span><span class="title_intro">施放一波气功弹，能击退面向的敌人，并对直线上所有的敌人造成大量魔法伤害，气功弹在飞行结束后会爆炸，造成海量魔法伤害，并使周围单位眩晕。</span></li>',
			'bsqy':'<li><span class="title_name">苗星仁：</span><span class="title_intro">故意接近青橙，靠翩翩君子的外形骗到了许多人。</span></li><li><span class="title_name">邓廷芳：</span><span class="title_intro">从小暗恋青橙，不过胆子有点小。</span></li>',
			'heroImgSrc_big':'<img src="img/b-lqc.png" alt="">',
			'heroImgSrc_small':'img/s-lqc.jpg'
			},
			{
			'name':'蔡八斗',
			'intro':'龙门镖局厨子兼任当家助理，执着憨厚，梦想是老婆孩子热炕头，只要有钱拿，除了犯法的事啥事都干。',
			'wuqi':'拳掌',
			'dir':'近战',
			'xl':21644,
			'wf':1290,
			'nf':764,
			'specialSrc':'<img src="img/k-cbd.png" alt="">',
			'skill':'<li><span class="title_name">四方连拳：</span><span class="title_intro">对一个敌人连续攻击，造成物理伤害，且暂时提高自身闪避。</span></li><li><span class="title_name">伏虎心决：</span><span class="title_intro">永久增加自身生命上限。</span></li><li><span class="title_name">降龙心决：</span><span class="title_intro">永久增加自身物理防御。</span></li><li><span class="title_name">暹罗秘药（大招）：</span><span class="title_intro">喝下来至暹罗的秘药，提升自身大量物理防御。</span></li>',
			'bsqy':'<li><span class="title_name">蔡二斗：</span><span class="title_intro">八斗的老哥，收拾八斗毫不留情。</span></li><li><span class="title_name">杨思维：</span><span class="title_intro">曾与八斗约定私奔，最后不了了之。</span></li>',
			'heroImgSrc_big':'<img src="img/b-cbd.png" alt="">',
			'heroImgSrc_small':'img/s-cbd.jpg'
			},
			{
			'name':'邱璎珞',
			'intro':'龙门镖局骨科大夫，祖上是宫廷御医，剩女一枚，超级花痴，喜欢帅哥，梦想嫁入豪门。',
			'wuqi':'银针',
			'dir':'远程',
			'xl':14917,
			'wf':720,
			'nf':856,
			'specialSrc':'<img src="img/k-qyl.png" alt="">',
			'skill':'<li><span class="title_name">清心诀：</span><span class="title_intro">使自身在进入战斗后，能自动缓缓恢复生命值。</span></li><li><span class="title_name">媚电之眼：</span><span class="title_intro">魅惑一名敌方对其造成魔法伤害，并使其眩晕。</span></li><li><span class="title_name">菩提心法：</span><span class="title_intro">永久增加自身魔法攻击力。</span></li><li><span class="title_name">妙手回春（大招）：</span><span class="title_intro">除自身外，治疗全体队友，恢复大量生命值。</span></li>',
			'bsqy':'<li><span class="title_name">灵儿：</span><span class="title_intro">长期为璎珞提供新款胭脂。</span></li><li><span class="title_name">曼曼：</span><span class="title_intro">长期为璎珞提供潮流服饰。</span></li>',
			'heroImgSrc_big':'<img src="img/b-qyl.png" alt="">',
			'heroImgSrc_small':'img/s-qyl.jpg'
			},
			{
			'name':'佟承畴',
			'intro':'盛秋月丈夫，龙门镖局前任当家，性格温文尔雅，并且身怀绝技，枪法高深，为掩护恭叔逃跑与劫镖贼人同归于尽。',
			'wuqi':'青龙月牙枪',
			'dir':'近战',
			'xl':'?',
			'wf':'?',
			'nf':'?',
			'specialSrc':'<img src="img/k-tcc.png" alt="">',
			'skill':'<li><span class="title_name">灵体虚化：</span><span class="title_intro">永久增加自身闪避，效果期间减免所受物外功害。</span></li><li><span class="title_name">幽魂附体：</span><span class="title_intro">施放一个幽魂分身附着在敌人身上，操控敌人互相攻击，被附着的敌人总共受到内功伤害。</span></li><li><span class="title_name">鬼魅之影：</span><span class="title_intro">召唤出两个鬼魅分身帮助战斗。</span></li><li><span class="title_name">连环飞枪：</span><span class="title_intro">对目标连射出10只飞矛，总共造成外功伤害，若在有鬼魅分身时，分身也会使用连环飞抢。</span></li>',
			'bsqy':'<li><span class="title_name">年功权：</span><span class="title_intro">佟承畴的老朋友，经常委托龙门镖局押镖。</span></li><li><span class="title_name">巩祥照：</span><span class="title_intro">一心要从龙门镖局要回欠款。</span></li>',
			'heroImgSrc_big':'<img src="img/b-tcc.png" alt="">',
			'heroImgSrc_small':'img/s-tcc.jpg'
			},
			{
			'name':'盛廷玉',
			'intro':'东厂督公，陆三金的大爷，因小时候被家中送进宫而怀恨在心，性格扭曲。',
			'wuqi':'拳掌',
			'dir':'远程',
			'xl':'?',
			'wf':'?',
			'nf':'?',
			'specialSrc':'<img src="img/k-syy.png" alt="">',
			'skill':'<li><span class="title_name">幻阴邪掌：</span><span class="title_intro">使对直线单位造成内功伤害。</span></li><li><span class="title_name">督公号令：</span><span class="title_intro">召唤两个东厂太监帮助战斗。</span></li><li><span class="title_name">葵花神功：</span><span class="title_intro">增加自身内功属性。</span></li><li><span class="title_name">幽冥鬼爪</span><span class="title_intro">对全屏单位造成内功伤害。</span></li>',
			'bsqy':'<li><span class="title_name">水生：</span><span class="title_intro">盛廷玉的下属，一直盘算着取而代之。</span></li><li><span class="title_name">沧月：</span><span class="title_intro">接东厂委托办事，办事效率不错。</span></li>',
			'heroImgSrc_big':'<img src="img/b-syy.png" alt="">',
			'heroImgSrc_small':'img/s-syy.jpg'
			},
			{
			'name':'司空追星',
			'intro':'自称青花会第一杀手,虽然是个瞎子，但能听见方圆五里内的声音，青花会解散后准备暗杀镖局众人，反被众人设计擒拿。',
			'wuqi':'拜月杖',
			'dir':'远程',
			'xl':'?',
			'wf':'?',
			'nf':'?',
			'specialSrc':'<img src="img/k-skzx.png" alt="">',
			'skill':'<li><span class="title_name">风月无边：</span><span class="title_intro">发出一道月旋转光波，攻击直线上的敌人，造成伤害。</span></li><li><span class="title_name">月华连斩：</span><span class="title_intro">发出3道半月波，随机攻击3名敌人，造成伤害。</span></li><li><span class="title_name">银月音波刀：</span><span class="title_intro">永久增加内功伤害，使施放技能时，有几率对敌人产生回音效果，回音中的敌人闪避率下降。</span></li><li><span class="title_name">明月千里：</span><span class="title_intro">施放多阵月光波，攻击战场中所有敌人，造成内功伤害，若目标身上有回音buff时，则会再施放一波月光攻击目标，造成内功伤害，并将目标眩晕。</span></li>',
			'bsqy':'<li><span class="title_name">龚磬冬：</span><span class="title_intro">司空追星的同事，主要负责行政。</span></li><li><span class="title_name">南宫残红：</span><span class="title_intro">司空追星的老上司，虽然管理方式有点问题。</span></li>',
			'heroImgSrc_big':'<img src="img/b-skzx.png" alt="">',
			'heroImgSrc_small':'img/s-skzx.jpg'
			},
			{
			'name':'黄一平',
			'intro':'邱璎珞的前男友，号称神医“黄三针”，和邱家世代为敌，为做一个好大夫放下了与璎珞的感情。',
			'wuqi':'银针',
			'dir':'远程',
			'xl':'?',
			'wf':'?',
			'nf':'?',
			'specialSrc':'<img src="img/k-hyp.png" alt="">',
			'skill':'<li><span class="title_name">金针度人：</span><span class="title_intro">施放一串飞针，对一个单位连续造成物理伤害。</span></li><li><span class="title_name">三针封喉：</span><span class="title_intro">永久增加自身攻击速度。施放时能封住目标的行动数秒，数秒后对目标造成内功伤害。</span></li><li><span class="title_name">法灸神针：</span><span class="title_intro">对一个友军进行针灸治疗，恢复生命值。</span></li><li><span class="title_name">针如雨注：</span><span class="title_intro">施放大量飞针，对全屏敌人造成物理伤害。</span></li>',
			'bsqy':'<li><span class="title_name">薇薇安：</span><span class="title_intro">黄一平的同行，主攻心理治疗。</span></li><li><span class="title_name">大黄蜂：</span><span class="title_intro">不知是黄一平从哪里抓到的奇异灵兽。</span></li>',
			'heroImgSrc_big':'<img src="img/b-hyp.png" alt="">',
			'heroImgSrc_small':'img/s-hyp.jpg'
			},
			{
			'name':'红凤凰',
			'intro':'恭叔前女友，塞外博雅族人，精通蛊术，据说能够沟通塔斯卡那神以施法招魂，对恭叔一往情深。',
			'wuqi':'招魂铃',
			'dir':'远程',
			'xl':'?',
			'wf':'?',
			'nf':'?',
			'specialSrc':'<img src="img/k-hfh.png" alt="">',
			'skill':'<li><span class="title_name">摄魂音：</span><span class="title_intro">对目标施放魔音，对目标其周围的单位造成内功伤害。</span></li><li><span class="title_name">离魄曲：</span><span class="title_intro">用招魂铃摇魔曲，对战场中3个敌人施放3道音波，对其造成内功伤害。</span></li><li><span class="title_name">离魄曲：</span><span class="title_intro">从当前目标身上吸取生命值，并有一定几率召唤小鬼，小鬼最多召唤3个。</span></li><li><span class="title_name">三才鬼阵：</span><span class="title_intro">召唤出一个巨大胖鬼魂帮助战斗。召唤时战场中的小鬼越多召唤出的胖鬼越厉害，胖鬼魂持续数秒。</span></li>',
			'bsqy':'<li><span class="title_name">阿美：</span><span class="title_intro">据称经常与红凤凰开展交流活动。</span></li><li><span class="title_name">红蜘蛛：</span><span class="title_intro">红凤凰豢养的毒兽。</span></li>',
			'heroImgSrc_big':'<img src="img/b-hfh.png" alt="">',
			'heroImgSrc_small':'img/s-hfh.jpg'
			}
		],
	'blueArr':
		[
			{
			'name':'陆三水',
			'intro':'陆三金的妹妹，傲娇卖萌白富美，毒舌技能MAX，盲目崇拜三金哥哥。',
			'wuqi':'拳掌',
			'dir':'近战',
			'xl':6281,
			'wf':586,
			'nf':424,
			'specialSrc':'<img src="img/k-lss.png" alt="">',
			'skill':'<li><span class="title_name">降书令：</span><span class="title_intro">对战场上所有的敌人发降书令，恐吓他们，期间造成内功伤害。若目标生命低于一定数值则有一定几率直接逃离战场（只对普通怪物有效），效果持续数秒。</span></li><li><span class="title_name">毒舌MAX：</span><span class="title_intro">每次攻击敌人时有几率用嘴炮扰乱敌人，受到物理伤害，且使该目标眩晕数秒。</span></li><li><span class="title_name">口水MAX：</span><span class="title_intro">对当前面向敌人喷出水浪，造成内功伤害，并降低目标攻击速度和移动速度，持续数秒。</span></li>',
			'bsqy':'<li><span class="title_name">陆三金：</span><span class="title_intro">三水的大哥，小时候经常欺负三水。</span></li><li><span class="title_name">陆三木：</span><span class="title_intro">三水的的二哥，经常教三水一些酸言酸语。</span></li>',
			'heroImgSrc_big':'<img src="img/b-lss.png" alt="">',
			'heroImgSrc_small':'img/s-lss.jpg'
			},
			{
			'name':'糊糊',
			'intro':'盛秋月儿子，龙门镖局吉祥物，调皮可爱，聪明伶俐，喜欢恶搞三金叔叔。',
			'wuqi':'弹弓',
			'dir':'远程',
			'xl':'?',
			'wf':'?',
			'nf':'?',
			'specialSrc':'<img src="img/k-hh.png" alt="">',
			'skill':'<li><span class="title_name">木蛙陷阱：</span><span class="title_intro">施放一只木蛙挡在自身面前，碰到木蛙的敌人会被咬伤，造成内功伤害，并且眩晕数秒。若放置木蛙数秒后无人触发，则木蛙自动寻找最近的目标攻击。</span></li><li><span class="title_name">乾坤弹球：</span><span class="title_intro">使用乾坤弹球代替石子做子弹，永久增加自外功攻击，使用一石二鸟技能时可提高其弹跳次数。</span></li><li><span class="title_name">一石二鸟：</span><span class="title_intro">对当前正在攻击的目标施放弹弓攻击造成物理伤害，并且会弹跳1次最近的的目标单位。</span></li>',
			'bsqy':'<li><span class="title_name">盛秋月：</span><span class="title_intro">糊糊的老妈，总被糊糊惹生气。</span></li><li><span class="title_name">山鸡：</span><span class="title_intro">糊糊长大后可以跟着学习砍刀的使用技巧。</span></li>',
			'heroImgSrc_big':'<img src="img/b-unknown.png" alt="">',
			'heroImgSrc_small':'img/s-unknown.jpg'
			},
			{
			'name':'厉文婷',
			'intro':'恭叔前女友，西南地区大姐大，人称黑道第一美女，目前洗白做连锁商铺。',
			'wuqi':'拳掌',
			'dir':'远程',
			'xl':5578,
			'wf':814,
			'nf':534,
			'specialSrc':'<img src="img/k-lwt.png" alt="">',
			'skill':'<li><span class="title_name">天仙采茶：</span><span class="title_intro">对当前攻击目标一定范围内的单位造成内功伤害（最多攻击5个单位）。</span></li><li><span class="title_name">江湖通缉：</span><span class="title_intro">对战场上所有的敌人发布通缉，使他们受到内功伤害，且降低其外功防御，效果持续数秒。</span></li><li><span class="title_name">一姐号令：</span><span class="title_intro">在西南一姐的引领下，全对增加攻击速度。</span></li>',
			'bsqy':'<li><span class="title_name">温良恭：</span><span class="title_intro">厉文婷的前男友，当时化名慕容。</span></li><li><span class="title_name">龚露：</span><span class="title_intro">某种意义上也算是情敌吧。</span></li>',
			'heroImgSrc_big':'<img src="img/b-lwt.png" alt="">',
			'heroImgSrc_small':'img/s-lwt.jpg'
			},
			{
			'name':'浩天',
			'intro':'和白敬祺从小一起长大，据说是个GAY，喜欢白敬祺，并将祖传戒指赠与小白。',
			'wuqi':'拳掌',
			'dir':'近战',
			'xl':15421,
			'wf':1135,
			'nf':536,
			'specialSrc':'<img src="img/k-ht.png" alt="">',
			'skill':'<li><span class="title_name">八卦掌：</span><span class="title_intro">对目标及其周围的单位造内功伤害。并使其进入内伤状态，内伤中的敌人不能使用技能攻击，持续数秒。</span></li><li><span class="title_name">天乾地坤：</span><span class="title_intro">增加内功防御和外功防御。</span></li><li><span class="title_name">八卦回天：</span><span class="title_intro">对自身大范围内的敌人连续造成内功伤害，期间己方单位所受伤害减免一定数值。持续数秒。</span></li>',
			'bsqy':'<li><span class="title_name">白敬祺：</span><span class="title_intro">浩天的发小，不了解浩天对自己的感情。</span></li><li><span class="title_name">冉湘：</span><span class="title_intro">某种意义上也算是情敌吧。</span></li>',
			'heroImgSrc_big':'<img src="img/b-ht.png" alt="">',
			'heroImgSrc_small':'img/s-ht.jpg'
			},
			{
			'name':'苗星仁',
			'intro':'佘山派传人，高尔夫球技高超，就职于东厂，风度翩翩，一表人才，迷倒万千少女。',
			'wuqi':'高尔夫球杆',
			'dir':'远程',
			'xl':'?',
			'wf':'?',
			'nf':'?',
			'specialSrc':'<img src="img/k-mxr.png" alt="">',
			'skill':'<li><span class="title_name">极限发球：</span><span class="title_intro">打出弧形飞球，攻击战场上敌方的后排敌人，对目标造成外功伤害。</span></li><li><span class="title_name">爆裂球弹：</span><span class="title_intro">使用大号的爆裂球弹，使球弹在击中目标后产生爆炸，造成内功伤害。</span></li><li><span class="title_name">佘山高尔夫：</span><span class="title_intro">对目标施放飞球攻击造成物理伤害，并且会弹跳2次最近的敌人。</span></li>',
			'bsqy':'<li><span class="title_name">吕青橙：</span><span class="title_intro">离家出走后与苗星仁度过一段开心的时光。</span></li><li><span class="title_name">邓廷芳：</span><span class="title_intro">从小暗恋青橙，不过胆子有点小。</span></li>',
			'heroImgSrc_big':'<img src="img/b-mxr.png" alt="">',
			'heroImgSrc_small':'img/s-mxr.jpg'
			},
			{
			'name':'蔡二斗',
			'intro':'八斗的哥哥，漕帮代表，从小当兵，恪守规矩，有事没事揍八斗，是八斗的童年阴影。',
			'wuqi':'大船桨',
			'dir':'近战',
			'xl':9532,
			'wf':817,
			'nf':535,
			'specialSrc':'<img src="img/k-ced.png" alt="">',
			'skill':'<li><span class="title_name">翻江倒海（自动）：</span><span class="title_intro">对目标造成外功伤害，并将目标击飞数秒。</span></li><li><span class="title_name">逆水行舟：</span><span class="title_intro">每次被攻击时有一定几率增加自身双抗，最多叠加5层次。</span></li><li><span class="title_name">乘风破浪：</span><span class="title_intro">跳起奋力用船桨怒锤地面，对大范围的敌人造成内功伤害，并降敌人一定数值的攻击速度。</span></li>',
			'bsqy':'<li><span class="title_name">蔡八斗：</span><span class="title_intro">二斗的老弟，吃过无数耳光。</span></li><li><span class="title_name">杨思维：</span><span class="title_intro">曾与八斗约定私奔，最后不了了之。</span></li>',
			'heroImgSrc_big':'<img src="img/b-ced.png" alt="">',
			'heroImgSrc_small':'img/s-ced.jpg'
			},
			{
			'name':'灵儿',
			'intro':'胭脂铺老板娘，集时尚与美丽一身，而且在生意上经营有道，与星猫裁缝铺的曼曼是双胞胎，是曼曼的姐姐。',
			'wuqi':'胭脂彩弹',
			'dir':'远程',
			'xl':8026,
			'wf':832,
			'nf':366,
			'specialSrc':'<img src="img/k-ler.png" alt="">',
			'skill':'<li><span class="title_name">五彩缤纷：</span><span class="title_intro">射出5个彩弹攻击5个目标，造成物理伤害。</span></li><li><span class="title_name">冰晶玉脂：</span><span class="title_intro">释放1颗彩弹，攻击当前目标，减少其攻击速度。</span></li><li><span class="title_name">天降彩脂：</span><span class="title_intro">施放大量彩弹，对当前目标250范围内的单位造成持续伤害，总共造成物理伤害，持续数秒。</span></li>',
			'bsqy':'<li><span class="title_name">邱璎珞：</span><span class="title_intro">灵儿的老客户，买过的胭脂比你见过的女人都多。</span></li><li><span class="title_name">曼曼：</span><span class="title_intro">灵儿的好姐妹，两人经常暗地里较劲。</span></li>',
			'heroImgSrc_big':'<img src="img/b-ler.png" alt="">',
			'heroImgSrc_small':'img/s-ler.jpg'
			},
			{
			'name':'年功权',
			'intro':'万永商铺掌柜，与前龙门镖局总镖头佟承畴有十几年的交情，外似无情冷酷不讲情面，实则内心善良。',
			'wuqi':'玉如意',
			'dir':'近战',
			'xl':'?',
			'wf':'?',
			'nf':'?',
			'specialSrc':'<img src="img/k-ngq.png" alt="">',
			'skill':'<li><span class="title_name">招财进宝：</span><span class="title_intro">召唤一个大元宝从天而降，对区域内的敌人造成内功伤害。</span></li><li><span class="title_name">和气生财：</span><span class="title_intro">每节战斗结束后全队恢复生命值。</span></li><li><span class="title_name">一本万利：</span><span class="title_intro">牺牲自身生命值，为全队增加外功攻击。</span></li>',
			'bsqy':'<li><span class="title_name">佟承畴：</span><span class="title_intro">年功权的老朋友，从他那接过不少生意。</span></li><li><span class="title_name">巩祥照：</span><span class="title_intro">曾被年功权委托追讨欠款，结果被整的很惨。</span></li>',
			'heroImgSrc_big':'<img src="img/b-ngq.png" alt="">',
			'heroImgSrc_small':'img/s-ngq.jpg'
			},
			{
			'name':'水生',
			'intro':'盛廷玉的手下，平日阿谀奉承，实则内心狠毒，十分腹黑。',
			'wuqi':'苦无',
			'dir':'近战',
			'xl':'?',
			'wf':'?',
			'nf':'?',
			'specialSrc':'<img src="img/k-ss.png" alt="">',
			'skill':'<li><span class="title_name">隐遁术：</span><span class="title_intro">在脚下释放施放一枚烟雾弹，对敌人造成伤害，并提升自身闪避。</span></li><li><span class="title_name">疾攻术：</span><span class="title_intro">修炼疾攻之术，永久增加自身的攻击速度。</span></li><li><span class="title_name">分身术：</span><span class="title_intro">施放两个影分身，且攻击模式切换成远程模式，影分身会持续施放手里剑攻击。</span></li>',
			'bsqy':'<li><span class="title_name">盛廷玉：</span><span class="title_intro">水生的上司，以整水生为乐。</span></li><li><span class="title_name">沧月：</span><span class="title_intro">接东厂委托办事，办事效率不错。</span></li>',
			'heroImgSrc_big':'<img src="img/b-unknown.png" alt="">',
			'heroImgSrc_small':'img/s-unknown.jpg'
			},
			{
			'name':'龚磬冬',
			'intro':'南宫残红的助理，一级杀手，非常自恋，弱点是镜子。',
			'wuqi':'单(反)匕首',
			'dir':'近战',
			'xl':8554,
			'wf':695,
			'nf':361,
			'specialSrc':'<img src="img/k-gxd.png" alt="">',
			'skill':'<li><span class="title_name">凤翼天翔：</span><span class="title_intro">对自身周围的敌人造成外功伤害，使敌人短暂浮空，并对身上有流血状态的敌人造成额外内功伤害。</span></li><li><span class="title_name">有凤来仪：</span><span class="title_intro">短暂蓄力迅速对一个目标重刺一刀，对目标和目标身后的单位造成外功伤害，并对目标造成流血状态。</span></li><li><span class="title_name">凤鸣鹤唳：</span><span class="title_intro">对自身周围的3个单位造成外功伤害，并使其流血。</span></li>',
			'bsqy':'<li><span class="title_name">司空追星：</span><span class="title_intro">龚磬冬的同事，主要负责执行。</span></li><li><span class="title_name">南宫残红：</span><span class="title_intro">龚磬冬的老上司，虽然管理方式有点问题。</span></li>',
			'heroImgSrc_big':'<img src="img/b-gxd.png" alt="">',
			'heroImgSrc_small':'img/s-gxd.jpg'
			},
			{
			'name':'薇薇安',
			'intro':'恭叔的前女友，学贯中西，博览群书，留学归来后转职心理咨询师，专业解决情感问题。',
			'wuqi':'魔法书',
			'dir':'远程',
			'xl':'?',
			'wf':'?',
			'nf':'?',
			'specialSrc':'<img src="img/k-wwa.png" alt="">',
			'skill':'<li><span class="title_name">无：</span><span class="title_intro">无</span></li><li><span class="title_name">无：</span><span class="title_intro">无</span></li><li><span class="title_name">无：</span><span class="title_intro">无</span></li>',
			'bsqy':'<li><span class="title_name">黄一平：</span><span class="title_intro">薇薇安的同行，主攻肉体治疗。</span></li><li><span class="title_name">大黄蜂：</span><span class="title_intro">不知是黄一平从哪里抓到的奇异灵兽。</span></li>',
			'heroImgSrc_big':'<img src="img/b-unknown.png" alt="">',
			'heroImgSrc_small':'img/s-unknown.jpg'
			},
			{
			'name':'阿美',
			'intro':'马帮首领，从小和三金一起长大，性格直率，喜欢三金，酒量很大。',
			'wuqi':'马刀',
			'dir':'近战',
			'xl':'?',
			'wf':'?',
			'nf':'?',
			'specialSrc':'<img src="img/k-am.png" alt="">',
			'skill':'<li><span class="title_name">无：</span><span class="title_intro">无</span></li><li><span class="title_name">无：</span><span class="title_intro">无</span></li><li><span class="title_name">无：</span><span class="title_intro">无</span></li>',
			'bsqy':'<li><span class="title_name">红凤凰：</span><span class="title_intro">据称经常与阿美开展交流活动。</span></li><li><span class="title_name">红蜘蛛：</span><span class="title_intro">红凤凰豢养的毒兽。</span></li>',
			'heroImgSrc_big':'<img src="img/b-unknown.png" alt="">',
			'heroImgSrc_small':'img/s-unknown.jpg'
			}
		],
	'greenArr':
		[
			{
			'name':'陆三木',
			'intro':'陆三金的弟弟，文质彬彬口才佳，擅长花言巧语加金钱攻势，专业欺诈大师。',
			'wuqi':'折扇',
			'dir':'远程',
			'xl':6496,
			'wf':507,
			'nf':406,
			'specialSrc':'<img src="img/k-lsm.png" alt="">',
			'skill':'<li><span class="title_name">激励之心：</span><span class="title_intro">每数秒随机为己方1个队友激励，增加外功攻击，持续数秒。</span></li><li><span class="title_name">洗脑大法：</span><span class="title_intro">使战场上的3个敌方单位进入狂热状态，状态中持续损失生命，持续数秒，状态结束后会产生眩晕，持续数秒。</span></li>',
			'bsqy':'<li><span class="title_name">陆三金：</span><span class="title_intro">三木的老哥，看不上三木那一套忽悠人的手段。</span></li><li><span class="title_name">陆三水：</span><span class="title_intro">三木的小妹，偶尔学三木说话。</span></li>',
			'heroImgSrc_big':'<img src="img/b-lsm.png" alt="">',
			'heroImgSrc_small':'img/s-lsm.jpg'
			},
			{
			'name':'山鸡',
			'intro':'秋月帮第一大将，独门绝技旋风连环斩，纹身技能精通，独创密室逃脱游戏。',
			'wuqi':'西瓜刀',
			'dir':'近战',
			'xl':7372,
			'wf':551,
			'nf':315,
			'specialSrc':'<img src="img/k-sj.png" alt="">',
			'skill':'<li><span class="title_name">一马当先：</span><span class="title_intro">进场时增加自身攻速和移动速度。</span></li><li><span class="title_name">连环旋风斩：</span><span class="title_intro">对自身周围的敌人造成物理伤害，持续数秒。</span></li>',
			'bsqy':'<li><span class="title_name">盛秋月：</span><span class="title_intro">山鸡的带头大姐。</span></li><li><span class="title_name">糊糊：</span><span class="title_intro">准备长大后跟山鸡学用砍刀。</span></li>',
			'heroImgSrc_big':'<img src="img/b-sj.png" alt="">',
			'heroImgSrc_small':'img/s-sj.jpg'
			},
			{
			'name':'龚露',
			'intro':'恭叔前女友，星宿派高手，星座学专家，高丽美容归来，目前住在镖局对面，誓要带走恭叔。',
			'wuqi':'逍遥刀',
			'dir':'近战',
			'xl':7684,
			'wf':523,
			'nf':410,
			'specialSrc':'<img src="img/k-gl.png" alt="">',
			'skill':'<li><span class="title_name">情意绵绵刀：</span><span class="title_intro">永久增加自身内攻攻击力，且使普攻时有一定几率使敌人魅惑，持续数秒。</span></li><li><span class="title_name">星宿逍遥刀：</span><span class="title_intro">对自身前方直线范围内的单位造成内功伤害。</span></li>',
			'bsqy':'<li><span class="title_name">温良恭：</span><span class="title_intro">龚露的前男友，因星座原因分手。</span></li><li><span class="title_name">厉文婷：</span><span class="title_intro">某种意义上也算是情敌吧。</span></li>',
			'heroImgSrc_big':'<img src="img/b-gl.png" alt="">',
			'heroImgSrc_small':'img/s-gl.jpg'
			},
			{
			'name':'冉湘',
			'intro':'黑道七大杀手之一，奉命暗杀白敬祺，不过是个幸运E, 自作自受反被自己失手杀死。',
			'wuqi':'飞刀',
			'dir':'远程',
			'xl':6731,
			'wf':530,
			'nf':284,
			'specialSrc':'<img src="img/k-rx.png" alt="">',
			'skill':'<li><span class="title_name">香奈百花散：</span><span class="title_intro">每次扔出飞刀攻击时，有一定几率扔出涂油百花散的飞刀，对目标额外造成内功伤害。并且使目标眩晕数秒。</span></li><li><span class="title_name">鬼魅夺魂刀：</span><span class="title_intro">对身前的单位放出大量飞刀，总共造成物理伤害。</span></li>',
			'bsqy':'<li><span class="title_name">白敬祺：</span><span class="title_intro">和冉湘约定来世再见。</span></li><li><span class="title_name">浩天：</span><span class="title_intro">某种意义上也算是情敌吧。</span></li>',
			'heroImgSrc_big':'<img src="img/b-rx.png" alt="">',
			'heroImgSrc_small':'img/s-rx.jpg'
			},
			{
			'name':'邓廷芳',
			'intro':'现任青州知府，青橙和敬祺的故友，暗恋青橙。曾拜点苍山和鉴真人为师，学得一身堪舆玄空之术。',
			'wuqi':'算命罗盘',
			'dir':'远程',
			'xl':5434,
			'wf':439,
			'nf':374,
			'specialSrc':'<img src="img/k-dtf.png" alt="">',
			'skill':'<li><span class="title_name">雷动九天：</span><span class="title_intro">召唤一道落雷，对目标造成内功伤害。</span></li><li><span class="title_name">鬼风起云涌：</span><span class="title_intro">在敌方战场中心点召唤出一个巨型龙卷风，对周围的敌方总共造成伤害。并且会把敌人吸入旋风中心。持续数秒。</span></li>',
			'bsqy':'<li><span class="title_name">吕青橙：</span><span class="title_intro">邓廷芳的暗恋对象，不过青橙对他没有感觉。</span></li><li><span class="title_name">苗星仁：</span><span class="title_intro">故意接近青橙，靠翩翩君子的外形骗到了许多人。</span></li>',
			'heroImgSrc_big':'<img src="img/b-dtf.png" alt="">',
			'heroImgSrc_small':'img/s-dtf.jpg'
			},
			{
			'name':'杨思维',
			'intro':'被宠坏的将军府千金小姐，叛逆地渴望自由，幻想童话般的爱情，因毁容事件与八斗结下缘分。',
			'wuqi':'玩具人偶',
			'dir':'远程',
			'xl':'?',
			'wf':'?',
			'nf':'?',
			'specialSrc':'<img src="img/k-ysw.png" alt="">',
			'skill':'<li><span class="title_name">人偶合一：</span><span class="title_intro">永久增加自身内功攻击力。使布偶能持续灼烧自身周围的敌方单位，灼烧造成内功伤害。</span></li><li><span class="title_name">护身布偶：</span><span class="title_intro">对当前攻击目标召唤出一个木偶，木偶落下时对目标周围的敌人造成内功伤害，持续数秒。</span></li>',
			'bsqy':'<li><span class="title_name">蔡八斗：</span><span class="title_intro">曾与杨思维约定私奔，最后不了了之。</span></li><li><span class="title_name">蔡二斗：</span><span class="title_intro">差点和杨思维成一家人。</span></li>',
			'heroImgSrc_big':'<img src="img/b-ysw.png" alt="">',
			'heroImgSrc_small':'img/s-ysw.jpg'
			},
			{
			'name':'曼曼',
			'intro':'裁缝铺老板娘兼首席设计师，热爱挑战，喜欢在押镖中寻找设计灵感。',
			'wuqi':'缝衣针',
			'dir':'近战',
			'xl':'?',
			'wf':'?',
			'nf':'?',
			'specialSrc':'<img src="img/k-mm.png" alt="">',
			'skill':'<li><span class="title_name">无：</span><span class="title_intro">无</span></li><li><span class="title_name">无：</span><span class="title_intro">无</span></li>',
			'bsqy':'<li><span class="title_name">邱璎珞：</span><span class="title_intro">曼曼的老客户，买新衣服时从不吝啬。</span></li><li><span class="title_name">灵儿：</span><span class="title_intro">曼曼的好姐妹，两人经常暗地里较劲。</span></li>',
			'heroImgSrc_big':'<img src="img/b-unknown.png" alt="">',
			'heroImgSrc_small':'img/s-unknown.jpg'
			},
			{
			'name':'巩祥照',
			'intro':'追债专业户，人送外号大脑袋，喜欢玩炸弹，智商被三金完爆，最终靠放高利贷发家致富。',
			'wuqi':'引线炸弹',
			'dir':'远程',
			'xl':5114,
			'wf':526,
			'nf':260,
			'specialSrc':'<img src="img/k-gxz.png" alt="">',
			'skill':'<li><span class="title_name">同去西天：</span><span class="title_intro">死亡后会进行自爆，对大范围单位造成内功伤害。</span></li><li><span class="title_name">炸你全家：</span><span class="title_intro">对战场中的3个敌人扔出炸弹，爆炸产生范围伤害，造成内功伤害。</span></li>',
			'bsqy':'<li><span class="title_name">佟承畴：</span><span class="title_intro">年功权的老朋友，从他那接过不少生意。</span></li><li><span class="title_name">年功权：</span><span class="title_intro">委托巩祥照追讨欠款，最后也没拿到钱。</span></li>',
			'heroImgSrc_big':'<img src="img/b-gxz.png" alt="">',
			'heroImgSrc_small':'img/s-gxz.jpg'
			},
			{
			'name':'沧月',
			'intro':'断桥派门人，妩媚的飞贼，嗲声嗲气，将龙门镖局一众人耍得团团转。',
			'wuqi':'血滴子',
			'dir':'近战',
			'xl':'?',
			'wf':'?',
			'nf':'?',
			'specialSrc':'<img src="img/k-cy.png" alt="">',
			'skill':'<li><span class="title_name">飞龙探云：</span><span class="title_intro">手掌成锥，猛刺目标，对敌人造成外功伤害，并降低目标外功攻击，增加自身外功攻击。</span></li><li><span class="title_name">燕尾裁春：</span><span class="title_intro">施放血滴子对当前扇形范围的敌人照成外功伤害，当血滴子飞回时能再次对敌人造成外功伤害。</span></li>',
			'bsqy':'<li><span class="title_name">盛廷玉：</span><span class="title_intro">曾委托沧月执行秘密任务。</span></li><li><span class="title_name">水生：</span><span class="title_intro">曾委托沧月执行秘密任务。</span></li>',
			'heroImgSrc_big':'<img src="img/b-unknown.png" alt="">',
			'heroImgSrc_small':'img/s-unknown.jpg'
			},
			{
			'name':'南宫残红',
			'intro':'青花会幕后指使人，老奸巨猾，后被陆三金设计搞垮青花会，最终入狱。',
			'wuqi':'火枪',
			'dir':'近战',
			'xl':6439,
			'wf':717,
			'nf':321,
			'specialSrc':'<img src="img/k-ngcx.png" alt="">',
			'skill':'<li><span class="title_name">砍杀：</span><span class="title_intro">使用砍刀攻击近身的敌人，造成外功伤害。</span></li><li><span class="title_name">爆头：</span><span class="title_intro">对目标及其周围的敌人造成外功伤害。</span></li>',
			'bsqy':'<li><span class="title_name">司空追星：</span><span class="title_intro">南宫残红的手下干将，主要负责执行。</span></li><li><span class="title_name">龚磬冬：</span><span class="title_intro">南宫残红的手下干将，主要负责行政。</span></li>',
			'heroImgSrc_big':'<img src="img/b-unknown.png" alt="">',
			'heroImgSrc_small':'img/s-unknown.jpg'
			}
		]
}